[[workspace.metadata.dylint.libraries]]
git = "https://github.com/trailofbits/dylint"
pattern = [
    "examples/general",
    "examples/supplementary",
    "examples/restriction/assert_eq_arg_misordering",
    "examples/restriction/collapsible_unwrap",
    "examples/restriction/const_path_join",
    "examples/restriction/inconsistent_qualification",
    "examples/restriction/misleading_variable_name",
    "examples/restriction/question_mark_in_expression",
    "examples/restriction/ref_aware_redundant_closure_for_method_calls",
    "examples/restriction/suboptimal_pattern",
    "examples/restriction/try_io_result",
]
